name: Enforce Branch Name Convention

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(fix|feature|docs)- ]]; then
            echo "❌ Branch name must start with fix-, feature-, or docs-"
            echo "Success"
            exit 1
          fi
